### ISSUE TITLE
This repo's use

### ISSUE THREAD

**Issue by eutampieri** [algorithm-ninja/cmsocial#22]
I'd like to know this repo's relationship between this repo's in GitHub and the site CMS.di.unipi.it
Is it a beta and testing repo used to push new features into the site? And if so, how often are the commits pushed to the site?
I know it's not an issue, but I don't know where to put it.

**Comment by eutampieri** [comment]
I think i'll colse it...

**Comment by eutampieri** [comment]
Just changed my mind… maybe someone will see if I reopen it.

**Comment by wil93** [comment]
The "allenamenti" branch is the one linked to cms.di.unipi.it

As you can see [here](https://github.com/algorithm-ninja/cmsocial/tree/allenamenti) the branch is "28 commits ahead, 52 commits behind develop", so there are quite a lot of new features waiting to be published on cms.di.unipi.it (52 commits), but some features are specific for the website and can't yet be merged in the main repository (28 commits). We are slowly unifying all branches into one.

> how often are the commits pushed to the site?

We used to merge back on 'allenamenti' every new feature, but now we're waiting a bit because the develop branch has become unstable. We need to fix a few things first.

Closing, but feel free to continue the discussion :wink:

**Comment by eutampieri** [comment]
Ok, that's fine. I'd help if I knew how the CMS was made. I know a bit of Python but I see that it's using some strange libraries I don't know.

Eugenio Tampieri



> Il giorno 01 mar 2017, alle ore 04:18, William Di Luigi <notifications@github.com> ha scritto:
> 
> We used to merge back on 'allenamenti' every new feature, but now we're waiting a bit because the develop branch has become unstable. We need to fix a few

**Comment by wil93** [comment]
CMS is not a simple software, it's indeed very complex. Don't worry if you find it hard to grasp (I don't yet understand most of it :sweat:).

If you are just starting to use it, [here](http://cms.readthedocs.io/en/latest/Introduction.html#general-structure) you can find an overview of how CMS is split in different services.

For most CMS patches (those that I contributed, for example), you just need to understand whats under `cms/server/` (admin and contestant web interfaces), `cmscontrib/` (task.yaml / contest.yaml loaders, db updaters...), `cmsranking/` (for RankingWebServer) and `cmstaskenv/` (for cmsMake). Those last two should be, in my opinion, in separate repositories, as they are two programs almost indipendent from CMS.

**Comment by wil93** [comment]
Oh, and of course the most important thing: for any CMS question there is the official chat room at https://gitter.im/cms-dev/cms

**Comment by eutampieri** [comment]
Thanks

Eugenio Tampieri



> Il giorno 02 mar 2017, alle ore 03:34, William Di Luigi <notifications@github.com> ha scritto:
> 
> If you are just starting to use it, here you can find an overview of how CMS is split in different services.
> 
> For most CMS patches (those that I contributed, for example), you just need to understand whats under cms/server/ (admin and contestant web interfaces), cmscontrib/ (task.yaml / contest.yaml loaders, db updaters...), cmsranking/ (for RankingWebServer) and cmstaskenv/ (for cmsMake). Those last two should be, in my opinion, in
